Deployment Details update
mbrandenburger/fabric-rfcs pull request #30
Opened 2020-11-19 21:49 UTC by g2flyer

Following up to  discussion from PR #29. More specifically, 
* added subsection for the three deployment phases
* added section for key-distribution and corresponding pic
* numbering fix in enclave registration pic

2020-11-19 23:08 UTC, bvavala requested changes

2020-11-19 23:08 UTC, bvavala commented on text/0000-fabric-private-chaincode-lite.md
> +The command can be triggered either through the FPC Client SDK or the peer cli (see [earlier Deployment Section](#deployment)).
Reverting, because that sentence is intentional to avoid any reference to the peer cli since we are not touching it. 
```suggestion
The command can be triggered through the FPC Client SDK (see [earlier Deployment Section](#deployment)).
```

2020-11-19 23:08 UTC, bvavala commented on text/0000-fabric-private-chaincode-lite.md
> +the (first part of the) [key distribution](../images/fpc/full-detail/fpc-key-dist.png) protocols of the FPC specification.
The question here is: why, what problem does it solve?

This question does not find an answer in the RFC, because the key distribution is not part of FPC Lite.
Most importantly, excluding this part does not make the proposal less functional or less secure.
So why should the reviewers read that?
This will just raise unnecessary questions.

The RFC is _not_ describing the design documents.

2020-11-19 23:11 UTC, g2flyer commented on text/0000-fabric-private-chaincode-lite.md
> +the (first part of the) [key distribution](../images/fpc/full-detail/fpc-key-dist.png) protocols of the FPC specification.
the first part of that protocols _is_ part of FPC lite

2020-11-19 23:14 UTC, g2flyer commented on text/0000-fabric-private-chaincode-lite.md
> +The command can be triggered either through the FPC Client SDK or the peer cli (see [earlier Deployment Section](#deployment)).
well, we do actually have that code in the repo. But i'll revert ..

2020-11-20 11:15 UTC, mbrandenburger commented
Thanks Michael! Let me freeze this until we resolved this discussion offline.

2020-12-01 17:53 UTC, closed without merging